name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: List all files for debugging
      - name: List all files
        run: ls -R

      # Step 3: Build the writer application
      - name: Build the writer application
        working-directory: ./finder-app
        run: make all

      # Step 4: checkout submodule 
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run : git submodule update --init --recursive
      
        # Step 5: Grant execute permissions to full-test.sh
      - name: Grant execute permissions to full-test.sh
        working-directory: assignment-autotest
        run: chmod +x full-test.sh
        
      - name: Clean and recreate build directory
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake ..
          make
          
      # Step 6: Run full test
      - name: Run unit test
        run: ./full-test.sh
