
Create or update your .github/workflows/build.yml file to include the following steps:

yaml
Copy code
name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: List files for debugging
      - name: List files for debugging
        run: ls -R

      # Step 3: Build the application
      - name: Build the writer application
        working-directory: ./Embedded_Linux_assignments-main/finder-app
        run: make all

      # Step 4: Run full tests
      - name: Run full-test.sh
        working-directory: ./Embedded_Linux_assignments-main/assignment-autotest
        run: ./full-test.sh