name: Build and Test Writer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile writer.c
        run: gcc -o writer writer.c

      - name: Test writer
        run: ./writer testfile.txt "Hello, GitHub Actions!"